[eye]
distance = 20       # Distance between the two eyes

[eye.left]
width = 64          # Default width of the left eye
height = 64         # Default height of the left eye
roundness = 16      # Default roundness of the left eye

[eye.right]
width = 64          # Default width of the right eye
height = 64         # Default height of the right eye
roundness = 16      # Default roundness of the right eye

[color]
bg = "yellow"		# Apply only for color screens
eye = "red"		    # Apply only for color screens
# Values currently set to color 320x240 screen! for i2c oled use the nondev eyeconfig!