# Config for buttons should include the gpio number of the button and the commands to run.
# It needs separate lines for short/long press commands
main.plugins.gpiocontrol.gpios.17.short_press = "echo 'Short Press on GPIO 17'"
main.plugins.gpiocontrol.gpios.17.long_press = "echo 'Long Press on GPIO 17'"

# Config for encoders should include the gpio number of the encoder pins, the gpio number of the button pin, and the commands to run.
# It needs separate lines for up/down and short/long press commands.
main.plugins.gpiocontrol.encoder.a = 5
main.plugins.gpiocontrol.encoder.b = 6
main.plugins.gpiocontrol.encoder.button = 13
main.plugins.gpiocontrol.encoder.up_command = "echo 'Encoder Rotated Up'"
main.plugins.gpiocontrol.encoder.down_command = "echo 'Encoder Rotated Down'"
main.plugins.gpiocontrol.encoder.short_press = "echo 'Encoder Button Short Pressed'"
main.plugins.gpiocontrol.encoder.long_press = "echo 'Encoder Button Long Pressed'"

# Config for the waveshare Oled/LCD hw monitor (true/false/auto)
main.plugins.OLED-Stats2.invert_colors = auto # black background during day, black text at night